<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    <link rel="stylesheet" href="/css/spat.css" rel="stylesheet">

    <title>Server-Side Programming - <?php echo $view->pageTitle; ?></title>
</head>




    <nav>
        <ul>
            <li><a <a class="active" href="systemsDisplay.php"> Al Anwar Center Systems Display </a></li>
            <li><a href="shelves.php"> Al Hofuf Shelves Factory</a></li>
            <li><a href="kitchens.php">Global Kitchens</a></li>
            <li><a href="exhibition.php">World Exhibition Display Establishment</a></li>
        </ul>
    </nav>


       <main id="content" class="col-xs-6 col-sm-9 col-md-10">



